---
title: "Precipitations data"
author: "Jessica"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data descriptions

```{r }
library(ncdf4)
data <- nc_open("C:/Users/FRT/Downloads/Fall-2026/MATH-8830/Project/PRCP_2013.nc")
print(data)
#https://pjbartlein.github.io/REarthSysSci/netCDF.html

```

```{r}
# GET LATITUDE AND LONGITUDE
lat <- ncvar_get(data,"XLAT")

lon <- ncvar_get(data, "XLONG")

# GET TIME 
time <- ncvar_get(data,"Time")

# GET THE UNITS OF THE TIME
tunits <- ncatt_get(data,"Time","units")


```


```{r}
library(lattice)
library(RColorBrewer)
library(CFtime)

# decode time
cf <- CFtime(tunits$value, calendar = "proleptic_gregorian", time) # convert time to CFtime class
cf
```
```{r}
library(CFtime)
timestamps <- as_timestamp(cf) # get character-string times
timestamps
```
```{r}
time_cf <- parse_timestamps(cf, timestamps) # parse the string into date components
time_cf
```


## Plots



```{r}

```


